### ISSUE TITLE
Document : Keystone and swift timer configs

### ISSUE THREAD

**Issue by boopalans** [pndaproject/pnda-heat-templates#127] opened 2017-11-15 01:05 UTC
When deploying PNDA, some times, exit with 401 unauthorized error due to time out, The swift and keystone configuration to be updated in the Openstack setup.

**Comment by trsmith2** [comment] 2017-11-15 05:35
This is an OpenStack configuration issue, not a PNDA issue, and a duplicate of https://github.com/pndaproject/pnda-heat-templates/issues/64

**Closed as completed by trsmith2** 2017-11-15 05:35 UTC
